// <auto-generated />
using System;
using FA.JustBlog.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FA.JustBlog.Core.Migrations
{
    [DbContext(typeof(JustBlogContext))]
    [Migration("20221222135109_UpdateSampleData")]
    partial class UpdateSampleData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FA.JustBlog.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 1",
                            Name = "Category 1",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 1"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 2",
                            Name = "Category 2",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 2"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 3",
                            Name = "Category 3",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 3"
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 4",
                            Name = "Category 4",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 4"
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 5",
                            Name = "Category 5",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 5"
                        },
                        new
                        {
                            Id = 6,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 6",
                            Name = "Category 6",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 6"
                        },
                        new
                        {
                            Id = 7,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 7",
                            Name = "Category 7",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 7"
                        },
                        new
                        {
                            Id = 8,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 8",
                            Name = "Category 8",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 8"
                        },
                        new
                        {
                            Id = 9,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 9",
                            Name = "Category 9",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 9"
                        },
                        new
                        {
                            Id = 10,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 10",
                            Name = "Category 10",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 10"
                        },
                        new
                        {
                            Id = 11,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 11",
                            Name = "Category 11",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 11"
                        },
                        new
                        {
                            Id = 12,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 12",
                            Name = "Category 12",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 12"
                        },
                        new
                        {
                            Id = 13,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 13",
                            Name = "Category 13",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 13"
                        },
                        new
                        {
                            Id = 14,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 14",
                            Name = "Category 14",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 14"
                        },
                        new
                        {
                            Id = 15,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 15",
                            Name = "Category 15",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 15"
                        },
                        new
                        {
                            Id = 16,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 16",
                            Name = "Category 16",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 16"
                        },
                        new
                        {
                            Id = 17,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 17",
                            Name = "Category 17",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 17"
                        },
                        new
                        {
                            Id = 18,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 18",
                            Name = "Category 18",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 18"
                        },
                        new
                        {
                            Id = 19,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Category Description 19",
                            Name = "Category 19",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "category-urlslug 19"
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CommentHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Published")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RateCount")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalRate")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 7,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "WASHINGTON/KYIV, Dec 22 (Reuters) - President Volodymyr Zelenskiy told the U.S. Congress that aid to Ukraine was an investment in democracy and \"not charity\" as he invoked American battles against the Nazis in World War Two to press for more assistance for his country's war effort.\r\n\r\nZelenskiy's comments on Wednesday come as Republicans - some of whom have voiced increasing scepticism about sending so much aid to Ukraine - are set to take control of the U.S. House of Representatives from Democrats on Jan. 3.",
                            PostedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 58,
                            ShortDescription = "President Volodymyr Zelenskiy told the U.S. Congress that aid to Ukraine was an investment in democracy and \"not charity\" as he invoked American battles against the Nazis in World War Two to press for more assistance for his country's war effort.",
                            Status = 0,
                            Title = "Ukraine's Zelenskiy tells U.S. Congress aid is 'not charity', urges more support",
                            TotalRate = 99,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo1",
                            ViewCount = 22
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 7,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(2020, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "LONDON, Dec 22 (Reuters) - Trillions of dollars wiped off world stocks, bond market tantrums, whip-sawing currency and commodities and the collapse of a few crypto empires - 2022 has been perhaps the most turbulent year investors have ever seen, and for good reason.\r\n\r\nTallying the final numbers is useful but doesn't even come close to telling the whole story.\r\n\r\nYes, global equities are down $14 trillion and heading for their second worst year on record, but there have been nearly 300 interest rate hikes and a trio of 10%-plus rallies in that time making the volatility freakish.",
                            PostedOn = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 65,
                            ShortDescription = "LONDON, Dec 22 (Reuters) - Trillions of dollars wiped off world stocks, bond market tantrums, whip-sawing currency and commodities and the collapse of a few crypto empires - 2022 has been perhaps the most turbulent year investors have ever seen, and for good reason",
                            Status = 0,
                            Title = "How 2022 shocked, rocked and rolled global markets",
                            TotalRate = 21,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo2",
                            ViewCount = 15
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 8,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(2020, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:",
                            PostedOn = new DateTime(2020, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 75,
                            ShortDescription = "NEW YORK/LONDON, Dec 22 (Reuters) - Bankers in New York and London are bracing for year-end bonuses that recruiters estimate are 30% to 50% lower, while some may receive none at all as dealmaking sputters and economic gloom sets takes hold.",
                            Status = 0,
                            Title = "Banker bonuses go from boom to bust in jarring reversal",
                            TotalRate = 38,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo3",
                            ViewCount = 91
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(2020, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "A general view of hydrogen electrolysis plant called 'REFHYNE', one of the world's first green hydrogen plants, during a launch event at Shell's Rhineland refinery in Wesseling near Cologne, Germany, July 2, 2021. REUTERS/Thilo Schmuelgen.A general view of hydrogen electrolysis plant called 'REFHYNE', one of the world's first green hydrogen plants, during a launch event at Shell's Rhineland refinery in Wesseling near Cologne, Germany, July 2, 2021. REUTERS/Thilo Schmuelgen",
                            PostedOn = new DateTime(2020, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 32,
                            ShortDescription = "A general view of hydrogen electrolysis plant called 'REFHYNE', one of the world's first green hydrogen plants, during a launch event at Shell's Rhineland refinery in Wesseling near Cologne, Germany, July 2, 2021. REUTERS/Thilo Schmuelgen",
                            Status = 0,
                            Title = "Has green hydrogen sprung a leak?",
                            TotalRate = 85,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo4",
                            ViewCount = 75
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 8,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(2020, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "President Volodymyr Zelenskiy told the U.S. Congress that aid to Ukraine was an investment in democracy and \"not charity\" as he invoked American battles against the Nazis in World War Two to press for more assistance for his country's war effort.",
                            PostedOn = new DateTime(2020, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 25,
                            ShortDescription = "President Volodymyr Zelenskiy told the U.S. Congress that aid to Ukraine was an investment in democracy and \"not charity\" as he invoked American battles against the Nazis in World War Two to press for more assistance for his country's war effort.",
                            Status = 0,
                            Title = "Toshiba's preferred bidder to seal $10.6 bln loan deal this week -Yomiuri",
                            TotalRate = 152,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo5",
                            ViewCount = 33
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:6",
                            PostedOn = new DateTime(2018, 3, 27, 7, 58, 23, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 13,
                            ShortDescription = "Post ShortDescription demo:6",
                            Status = 0,
                            Title = "Post Title demo:6",
                            TotalRate = 83,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo6",
                            ViewCount = 16
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 6,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:7",
                            PostedOn = new DateTime(2019, 4, 30, 14, 46, 5, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 35,
                            ShortDescription = "Post ShortDescription demo:7",
                            Status = 0,
                            Title = "Post Title demo:7",
                            TotalRate = 138,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo7",
                            ViewCount = 38
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:8",
                            PostedOn = new DateTime(2017, 10, 11, 12, 39, 16, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 39,
                            ShortDescription = "Post ShortDescription demo:8",
                            Status = 0,
                            Title = "Post Title demo:8",
                            TotalRate = 95,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo8",
                            ViewCount = 87
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:9",
                            PostedOn = new DateTime(2021, 5, 24, 0, 20, 39, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 89,
                            ShortDescription = "Post ShortDescription demo:9",
                            Status = 0,
                            Title = "Post Title demo:9",
                            TotalRate = 72,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo9",
                            ViewCount = 35
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 9,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:10",
                            PostedOn = new DateTime(2007, 3, 5, 8, 12, 20, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 6,
                            ShortDescription = "Post ShortDescription demo:10",
                            Status = 0,
                            Title = "Post Title demo:10",
                            TotalRate = 77,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo10",
                            ViewCount = 19
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 8,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:11",
                            PostedOn = new DateTime(2020, 7, 8, 0, 15, 3, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 69,
                            ShortDescription = "Post ShortDescription demo:11",
                            Status = 0,
                            Title = "Post Title demo:11",
                            TotalRate = 196,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo11",
                            ViewCount = 9
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 8,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:12",
                            PostedOn = new DateTime(2022, 4, 14, 13, 49, 24, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 24,
                            ShortDescription = "Post ShortDescription demo:12",
                            Status = 0,
                            Title = "Post Title demo:12",
                            TotalRate = 117,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo12",
                            ViewCount = 72
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:13",
                            PostedOn = new DateTime(2011, 2, 9, 7, 1, 32, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 92,
                            ShortDescription = "Post ShortDescription demo:13",
                            Status = 0,
                            Title = "Post Title demo:13",
                            TotalRate = 145,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo13",
                            ViewCount = 89
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:14",
                            PostedOn = new DateTime(2003, 8, 23, 7, 58, 40, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 42,
                            ShortDescription = "Post ShortDescription demo:14",
                            Status = 0,
                            Title = "Post Title demo:14",
                            TotalRate = 121,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo14",
                            ViewCount = 6
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:15",
                            PostedOn = new DateTime(2007, 6, 12, 9, 4, 24, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 15,
                            ShortDescription = "Post ShortDescription demo:15",
                            Status = 0,
                            Title = "Post Title demo:15",
                            TotalRate = 158,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo15",
                            ViewCount = 69
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:16",
                            PostedOn = new DateTime(2003, 5, 11, 18, 56, 33, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 36,
                            ShortDescription = "Post ShortDescription demo:16",
                            Status = 0,
                            Title = "Post Title demo:16",
                            TotalRate = 63,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo16",
                            ViewCount = 5
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:17",
                            PostedOn = new DateTime(2004, 1, 31, 23, 36, 41, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 81,
                            ShortDescription = "Post ShortDescription demo:17",
                            Status = 0,
                            Title = "Post Title demo:17",
                            TotalRate = 43,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo17",
                            ViewCount = 54
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:18",
                            PostedOn = new DateTime(2013, 3, 21, 1, 42, 16, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 71,
                            ShortDescription = "Post ShortDescription demo:18",
                            Status = 0,
                            Title = "Post Title demo:18",
                            TotalRate = 37,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo18",
                            ViewCount = 98
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:19",
                            PostedOn = new DateTime(2015, 11, 27, 5, 2, 18, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 94,
                            ShortDescription = "Post ShortDescription demo:19",
                            Status = 0,
                            Title = "Post Title demo:19",
                            TotalRate = 128,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo19",
                            ViewCount = 88
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:20",
                            PostedOn = new DateTime(2004, 11, 16, 10, 37, 5, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 97,
                            ShortDescription = "Post ShortDescription demo:20",
                            Status = 0,
                            Title = "Post Title demo:20",
                            TotalRate = 36,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo20",
                            ViewCount = 46
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:21",
                            PostedOn = new DateTime(2016, 7, 6, 4, 6, 43, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 95,
                            ShortDescription = "Post ShortDescription demo:21",
                            Status = 0,
                            Title = "Post Title demo:21",
                            TotalRate = 134,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo21",
                            ViewCount = 12
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:22",
                            PostedOn = new DateTime(2001, 3, 12, 5, 10, 57, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 9,
                            ShortDescription = "Post ShortDescription demo:22",
                            Status = 0,
                            Title = "Post Title demo:22",
                            TotalRate = 81,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo22",
                            ViewCount = 62
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:23",
                            PostedOn = new DateTime(2005, 6, 5, 5, 33, 21, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 46,
                            ShortDescription = "Post ShortDescription demo:23",
                            Status = 0,
                            Title = "Post Title demo:23",
                            TotalRate = 165,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo23",
                            ViewCount = 28
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:24",
                            PostedOn = new DateTime(2017, 5, 8, 13, 41, 40, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 2,
                            ShortDescription = "Post ShortDescription demo:24",
                            Status = 0,
                            Title = "Post Title demo:24",
                            TotalRate = 173,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo24",
                            ViewCount = 57
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:25",
                            PostedOn = new DateTime(2002, 3, 1, 1, 54, 32, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 76,
                            ShortDescription = "Post ShortDescription demo:25",
                            Status = 0,
                            Title = "Post Title demo:25",
                            TotalRate = 70,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo25",
                            ViewCount = 63
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 9,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:26",
                            PostedOn = new DateTime(2001, 6, 6, 1, 20, 33, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 76,
                            ShortDescription = "Post ShortDescription demo:26",
                            Status = 0,
                            Title = "Post Title demo:26",
                            TotalRate = 17,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo26",
                            ViewCount = 21
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:27",
                            PostedOn = new DateTime(2002, 7, 20, 15, 47, 3, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 78,
                            ShortDescription = "Post ShortDescription demo:27",
                            Status = 0,
                            Title = "Post Title demo:27",
                            TotalRate = 186,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo27",
                            ViewCount = 76
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:28",
                            PostedOn = new DateTime(2018, 9, 30, 6, 51, 54, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 35,
                            ShortDescription = "Post ShortDescription demo:28",
                            Status = 0,
                            Title = "Post Title demo:28",
                            TotalRate = 140,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo28",
                            ViewCount = 61
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:29",
                            PostedOn = new DateTime(2003, 9, 4, 12, 1, 0, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 47,
                            ShortDescription = "Post ShortDescription demo:29",
                            Status = 0,
                            Title = "Post Title demo:29",
                            TotalRate = 86,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo29",
                            ViewCount = 36
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 9,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:30",
                            PostedOn = new DateTime(2009, 6, 3, 13, 3, 23, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 45,
                            ShortDescription = "Post ShortDescription demo:30",
                            Status = 0,
                            Title = "Post Title demo:30",
                            TotalRate = 40,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo30",
                            ViewCount = 81
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:31",
                            PostedOn = new DateTime(2008, 11, 27, 6, 51, 23, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 61,
                            ShortDescription = "Post ShortDescription demo:31",
                            Status = 0,
                            Title = "Post Title demo:31",
                            TotalRate = 57,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo31",
                            ViewCount = 10
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:32",
                            PostedOn = new DateTime(2016, 6, 12, 17, 1, 1, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 95,
                            ShortDescription = "Post ShortDescription demo:32",
                            Status = 0,
                            Title = "Post Title demo:32",
                            TotalRate = 172,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo32",
                            ViewCount = 24
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:33",
                            PostedOn = new DateTime(2000, 3, 3, 4, 8, 20, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 37,
                            ShortDescription = "Post ShortDescription demo:33",
                            Status = 0,
                            Title = "Post Title demo:33",
                            TotalRate = 131,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo33",
                            ViewCount = 98
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:34",
                            PostedOn = new DateTime(2017, 12, 8, 23, 19, 20, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 32,
                            ShortDescription = "Post ShortDescription demo:34",
                            Status = 0,
                            Title = "Post Title demo:34",
                            TotalRate = 175,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo34",
                            ViewCount = 2
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:35",
                            PostedOn = new DateTime(2005, 7, 24, 21, 57, 58, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 99,
                            ShortDescription = "Post ShortDescription demo:35",
                            Status = 0,
                            Title = "Post Title demo:35",
                            TotalRate = 94,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo35",
                            ViewCount = 30
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:36",
                            PostedOn = new DateTime(2017, 3, 26, 12, 38, 39, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 2,
                            ShortDescription = "Post ShortDescription demo:36",
                            Status = 0,
                            Title = "Post Title demo:36",
                            TotalRate = 113,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo36",
                            ViewCount = 31
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 9,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:37",
                            PostedOn = new DateTime(2000, 9, 23, 18, 29, 9, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 5,
                            ShortDescription = "Post ShortDescription demo:37",
                            Status = 0,
                            Title = "Post Title demo:37",
                            TotalRate = 140,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo37",
                            ViewCount = 10
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:38",
                            PostedOn = new DateTime(2008, 8, 20, 1, 18, 8, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 64,
                            ShortDescription = "Post ShortDescription demo:38",
                            Status = 0,
                            Title = "Post Title demo:38",
                            TotalRate = 44,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo38",
                            ViewCount = 74
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:39",
                            PostedOn = new DateTime(2016, 1, 26, 9, 10, 44, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 10,
                            ShortDescription = "Post ShortDescription demo:39",
                            Status = 0,
                            Title = "Post Title demo:39",
                            TotalRate = 93,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo39",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:40",
                            PostedOn = new DateTime(2021, 10, 6, 9, 36, 50, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 36,
                            ShortDescription = "Post ShortDescription demo:40",
                            Status = 0,
                            Title = "Post Title demo:40",
                            TotalRate = 69,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo40",
                            ViewCount = 87
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 9,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:41",
                            PostedOn = new DateTime(2015, 2, 14, 17, 58, 46, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 12,
                            ShortDescription = "Post ShortDescription demo:41",
                            Status = 0,
                            Title = "Post Title demo:41",
                            TotalRate = 76,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo41",
                            ViewCount = 18
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:42",
                            PostedOn = new DateTime(2011, 1, 3, 22, 38, 32, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 9,
                            ShortDescription = "Post ShortDescription demo:42",
                            Status = 0,
                            Title = "Post Title demo:42",
                            TotalRate = 76,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo42",
                            ViewCount = 33
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 6,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:43",
                            PostedOn = new DateTime(2015, 10, 16, 5, 2, 48, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 60,
                            ShortDescription = "Post ShortDescription demo:43",
                            Status = 0,
                            Title = "Post Title demo:43",
                            TotalRate = 97,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo43",
                            ViewCount = 88
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:44",
                            PostedOn = new DateTime(2004, 2, 11, 14, 13, 10, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 1,
                            ShortDescription = "Post ShortDescription demo:44",
                            Status = 0,
                            Title = "Post Title demo:44",
                            TotalRate = 50,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo44",
                            ViewCount = 33
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:45",
                            PostedOn = new DateTime(2011, 10, 17, 3, 21, 24, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 71,
                            ShortDescription = "Post ShortDescription demo:45",
                            Status = 0,
                            Title = "Post Title demo:45",
                            TotalRate = 36,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo45",
                            ViewCount = 13
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 9,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:46",
                            PostedOn = new DateTime(2022, 12, 4, 18, 11, 23, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 74,
                            ShortDescription = "Post ShortDescription demo:46",
                            Status = 0,
                            Title = "Post Title demo:46",
                            TotalRate = 101,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo46",
                            ViewCount = 26
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:47",
                            PostedOn = new DateTime(2000, 10, 22, 5, 32, 46, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 30,
                            ShortDescription = "Post ShortDescription demo:47",
                            Status = 0,
                            Title = "Post Title demo:47",
                            TotalRate = 98,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo47",
                            ViewCount = 1
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:48",
                            PostedOn = new DateTime(2013, 6, 3, 22, 17, 36, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 67,
                            ShortDescription = "Post ShortDescription demo:48",
                            Status = 0,
                            Title = "Post Title demo:48",
                            TotalRate = 177,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo48",
                            ViewCount = 15
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Post PostContent demo:49",
                            PostedOn = new DateTime(2011, 6, 15, 8, 34, 26, 0, DateTimeKind.Unspecified),
                            Published = 0,
                            RateCount = 46,
                            ShortDescription = "Post ShortDescription demo:49",
                            Status = 0,
                            Title = "Post Title demo:49",
                            TotalRate = 1,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "post-urlslug-demo49",
                            ViewCount = 34
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.PostTagMap", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("TagId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("PostTagMaps");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            PostId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            TagId = 2,
                            PostId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            TagId = 3,
                            PostId = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            TagId = 1,
                            PostId = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            TagId = 2,
                            PostId = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            TagId = 3,
                            PostId = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            TagId = 1,
                            PostId = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            TagId = 5,
                            PostId = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 1,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Description demo:1",
                            Name = "instagram",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "tag-urlslug-demo1"
                        },
                        new
                        {
                            Id = 2,
                            Count = 2,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Description demo:2",
                            Name = "love",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "tag-urlslug-demo2"
                        },
                        new
                        {
                            Id = 3,
                            Count = 3,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Description demo:3",
                            Name = "like",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "tag-urlslug-demo3"
                        },
                        new
                        {
                            Id = 4,
                            Count = 4,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Description demo:4",
                            Name = "instagood",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "tag-urlslug-demo4"
                        },
                        new
                        {
                            Id = 5,
                            Count = 5,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Description demo:5",
                            Name = "follow",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "tag-urlslug-demo5"
                        },
                        new
                        {
                            Id = 6,
                            Count = 6,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Description demo:6",
                            Name = "likeforlikes",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "tag-urlslug-demo6"
                        },
                        new
                        {
                            Id = 7,
                            Count = 7,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Description demo:7",
                            Name = "viral",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "tag-urlslug-demo7"
                        },
                        new
                        {
                            Id = 8,
                            Count = 8,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Description demo:8",
                            Name = "new",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "tag-urlslug-demo8"
                        },
                        new
                        {
                            Id = 9,
                            Count = 9,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Description demo:9",
                            Name = "photography",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "tag-urlslug-demo9"
                        },
                        new
                        {
                            Id = 10,
                            Count = 91,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Description demo:10",
                            Name = "meme",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "tag-urlslug-demo10"
                        },
                        new
                        {
                            Id = 11,
                            Count = 92,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Description demo:11",
                            Name = "girl",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "tag-urlslug-demo11"
                        },
                        new
                        {
                            Id = 12,
                            Count = 93,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Description demo:12",
                            Name = "explorepage",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "tag-urlslug-demo12"
                        },
                        new
                        {
                            Id = 13,
                            Count = 94,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Description demo:13",
                            Name = "india",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "tag-urlslug-demo13"
                        },
                        new
                        {
                            Id = 14,
                            Count = 95,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Description demo:14",
                            Name = "new",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "tag-urlslug-demo14"
                        },
                        new
                        {
                            Id = 15,
                            Count = 96,
                            CreateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tag Description demo:15",
                            Name = "car",
                            Status = 0,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UrlSlug = "tag-urlslug-demo15"
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Comment", b =>
                {
                    b.HasOne("FA.JustBlog.Core.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Post", b =>
                {
                    b.HasOne("FA.JustBlog.Core.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.PostTagMap", b =>
                {
                    b.HasOne("FA.JustBlog.Core.Models.Post", "Post")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FA.JustBlog.Core.Models.Tag", "Tag")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostTagMaps");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Tag", b =>
                {
                    b.Navigation("PostTagMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
